# Generated by Django 3.1.3 on 2021-01-10 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='p_class',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=32),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='sex',
            field=models.CharField(choices=[('0', 'Man'), ('1', 'Woman')], max_length=3),
        ),
        migrations.AlterField(
            model_name='counts',
            name='enter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
